Ability to provide scopes from the request into the security backends
greenpau/go-authcrunch pull request #19
Opened 2022-05-10 14:04 UTC by dbranco-sdc

While we cleaned up the fork repository, we loose the delivered [pull request](https://github.com/greenpau/go-authcrunch/pull/16). This is just a cleaner pull request with exact same content for the new feature.

As mentioned [here](https://github.com/greenpau/caddy-security/issues/70#issue-1165485078), here's the first part of implementing the mentioned feature, so that if the AdditionalScopes flag is enabled in PolicyConfig, Authcrunch will forward the additional scopes provided by the client and append those to the ones already set on the identity provider.

We have on a `caddy-security` fork the second part ready, which is a flag on Caddyfile which allows for this functionality to be enabled, however we need a new release prior to doing this change since we cannot do a `replace` in the go.mod file to our fork 😀.

After this is merged and released we will do a pull request for the second part.

2022-05-11 17:01 UTC, greenpau commented
@dbranco-sdc , for licensing purposes. Each person on the `Co-authored-by` must create its own PR with commit on `consent.yaml`. After they consented by creating the commits, I will accept this PR.

2022-05-13 12:59 UTC, dbranco-sdc commented
@greenpau. Hello, I have seen that you have already added Paula and Sergiu consent into your branch repo.

2022-05-13 13:33 UTC, greenpau commented
@dbranco-sdc , will re-review and merge over the weekend.

2022-05-16 13:07 UTC, greenpau commented
@dbranco-sdc , was not able to get to it over the weekend. Will try finding time on weekdays.

2022-05-20 05:35 UTC, greenpau commented
@dbranco-sdc , I just finished with my current work on UI. Please rebase and re-test.

2022-05-20 13:20 UTC, dbranco-sdc commented
> @dbranco-sdc , I just finished with my current work on UI. Please rebase and re-test.

It has been merge the latest changes from main into the pull request, and test still green

2022-05-20 13:29 UTC, greenpau commented on pkg/util/validate/additional_scopes.go
> +	compile, _ := regexp.Compile("^[\\w|\\s]+$")
@dbranco-sdc , please change to must compile and make it package-level.

2022-05-20 13:31 UTC, greenpau commented on pkg/authz/authenticate.go
> +			g.logger.Warn(err.Error())
@dbranco-sdc , please see other logger message for reference. We would need more things that just the error.

2022-05-20 13:31 UTC, greenpau commented on pkg/authz/handlers/redirect.go
> +		rr.Redirect.AuthURL = rr.Redirect.AuthURL + rr.Redirect.Separator + "additional_scopes" + "=" + escapedAdditionalScopes
@dbranco-sdc , please use `fmt.Sprintf` for this.

2022-05-20 13:33 UTC, greenpau commented on pkg/util/validate/additional_scopes.go
> +	match := compile.MatchString(additionalScopes)
@dbranco-sdc , could just be `if compile.MatchString ...`. Please rename `compile` to `pattern` or `r`.

2022-05-20 13:33 UTC, greenpau requested changes
@dbranco-sdc , please address my comments 👍

2022-05-20 15:15 UTC, dbranco-sdc commented
> @dbranco-sdc , please address my comments 👍

Please check the latest changes implementing your suggestions, thanks in advance

2022-05-22 17:15 UTC, merged

2022-05-22 17:16 UTC, greenpau commented
Thank you all for contributing! 👍

2022-05-23 01:05 UTC, greenpau commented
@dbranco-sdc , please help with https://github.com/greenpau/caddy-security/issues/108
It might be related to the redirect changes.