authn: add support for custom callback url
greenpau/go-authcrunch pull request #7
Opened 2022-03-01 12:59 UTC by simaotwx

Related: https://github.com/greenpau/caddy-security/issues/64

2022-03-05 15:57 UTC, greenpau requested changes
@simaotwx , thank you! 👍 Please add `b.Config.JsCallbackURL` too and handle the logic there too.

Additionally, how do you deal with 

https://github.com/greenpau/go-authcrunch/blob/27766dcc232658851a81f8bdcff7f8f73cb4a1cf/pkg/authn/handle_external_login.go#L30-L33

https://github.com/greenpau/go-authcrunch/blob/27766dcc232658851a81f8bdcff7f8f73cb4a1cf/pkg/authn/handle_external_login.go#L118-L124

2022-03-05 15:57 UTC, greenpau commented on pkg/authn/backends/oauth2/authenticate.go
> +			var reqRedirectURI string
@simaotwx , please use `switch` instead of `if/else`.

2022-03-05 15:57 UTC, greenpau commented on pkg/authn/backends/oauth2/authenticate.go
> +			if len(b.Config.CallbackUrl) > 0 {
@simaotwx , please replace `CallbackUrl` with `CallbackURL`.

2022-03-05 15:57 UTC, greenpau commented on pkg/authn/backends/oauth2/authenticate.go
>  	if b.Config.JsCallbackEnabled {
@simaotwx , please use `switch` instead of `if/else`.

2022-03-05 15:57 UTC, greenpau commented
@simaotwx , also, please add your CLA consent to this commit.

2022-03-05 15:58 UTC, greenpau commented
@simaotwx , additionally, please add tests.

2022-07-18 01:27 UTC, closed without merging

2022-07-25 16:07 UTC, steverweber commented
was this dropped or merged?

2022-07-25 16:10 UTC, simaotwx commented
@steverweber dropped. Haven't found the time to do all the things mentioned. Nevertheless, the commit works for my use case so you can pick it if you feel like you need it, too.